### ISSUE TITLE
macOS平台支持

### ISSUE THREAD

**Issue by shuai132** [Fancyflame/irisia-gui#11]
能支持一下macOS平台么？

我试了一下，目前编译倒是没问题。

可能有个不太好解决的问题：
winit的事件循环和渲染线程都需要是主线程（目前好像渲染是独立的线程）。
另一个难点是让主线程支持tokio的异步，而winit有独立的事件循环。

**Comment by Fancyflame** [comment]
macOS不是第一批兼容，不过放心，后续肯定也要兼容的。
macOS要求主线程渲染吗？其实问题也不大，在别的线程绘制好以后把结果发回主线程渲染就可以了。后面稍微调整一下就好了。

**Comment by shuai132** [comment]
如果渲染线程/主线程不需要用到tokio的话，问题应该不大~

**Comment by Fancyflame** [comment]
是的。主线程是全由winit控制的，和tokio runtime无关。没别的问题的话我关issue了哈，感谢关注irisia

**Comment by Fancyflame** [comment]
现在已支持MacOS
