### ISSUE TITLE
编译卡死在构建 `skia-bindings`

### ISSUE THREAD

**Issue by a1393323447** [Fancyflame/irisia-gui#3]
运行命令
```
 cargo run --release --example window
```
编译卡在构建 `skia-bindings`：
```
   Compiling pixels v0.12.1
    Building [=======================> ] 246/253: skia-bindings(build)
irisia-gui on git main [<] via rs v1.71.0-nightly took 16m9s
```
查看资源管理器：
![cpu](https://user-images.githubusercontent.com/72246322/235122680-8c8488ce-8634-459b-9d9f-cd7b21eaf224.PNG)
可以看到 `cargo` 的 `cpu` 占用率为 `0%` 。

## 配置
系统: windows 10 21H2
rust 版本: cargo 1.71.0-nightly (9e586fbd8 2023-04-25)

**Comment by fzdwx** [comment]
这个要等等

**Comment by Fancyflame** [comment]
这个因为是连接github所以一般是网络问题，看看irisia book里面有解决办法

**Comment by a1393323447** [comment]
@Fancyflame 是用什么连接 `github` 的？`git` 吗？如果是的话，我是开了梯子的。而且我等了16分钟也没有超时之类的错误。

**Comment by Fancyflame** [comment]
我不确定，因为skia_safe如果下载不到预编译包就会开始本地编译，有可能在本地编译skia了。用预编译包几秒钟就好了。
挂梯以后有没有设置`https_proxy`环境变量？
我是建议把预编译包下到本地存着，这样不用每次都挂梯

**Comment by a1393323447** [comment]
OK，确实是网络问题。麻烦了。
