### ISSUE TITLE
编译报错error: failed to run custom build command for `skia-bindings v0.62.0`

### ISSUE THREAD

**Issue by Xiaobaishushu25** [Fancyflame/irisia-gui#5]
我之前没有接触过skia，是需要自己拉源码编译skia吗？

**Comment by Fancyflame** [comment]
不用，看irisia-book，里面有说怎么办。咱国内都要手动下载编译包，设置环境变量后再编译。这个问题我记得已经有人已经问过了。
另外这个版本因为在处理缓存结构，的irisia的文本框还是旧结构没法编译，可以编译上个commit的。
