### ISSUE TITLE
examples里面的例子运行不起来

### ISSUE THREAD

**Issue by jluwoniu** [Fancyflame/irisia-gui#6]
error[E0432]: unresolved import `irisia_core::element::Frame`
 --> irisia\src\textbox\mod.rs:8:24
  |
8 |     element::{Element, Frame, InitContent},
  |                        ^^^^^ no `Frame` in `element`

**Comment by Fancyflame** [comment]
因为现在在做缓存系统，之前写的要修改，example暂时不能用了
回退一下commit到缓存系统开始前一个版本
```
git clone https://github.com/Fancyflame/irisia-gui.git
cd irisia-gui
git reset --hard f332664
cargo r --example window
```
我去改一下readme，跑起来了告诉我一声哈
