### ISSUE TITLE
为什么文档有部分无法查看？

### ISSUE THREAD

**Issue by c61292558** [Fancyflame/irisia-gui#8]
为什么文档有部分无法查看？只能看到几个，其他都无法点击。

**Comment by Fancyflame** [comment]
其他的还没写好，所以是灰色的。现有的文档也只有安装环境部分是有效的，其他部分都发生了大改动。irisia现在正在快速迭代，现在补文档很可能几周后就发生变化，发布第一个preview版本后会开始完善文档。
现在irisia还没办法开始测试，只能通过运行window example来提前获知irisia的功能和进度，还**不建议**用户开始学习。

**Comment by c61292558** [comment]
好的
